name: Deploy to Sormas CIF to the staging Server

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: CI=false yarn build

      - name: Copy artifact to staging
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_CICD_USER }}
          key: ${{ secrets.STAGING_YESK }}
          port: ${{ secrets.STAGING_PORT }}
          passphrase: ${{ secrets.STAGING_PHARSE }}
          strip_components: 1
          overwrite: true
          source: $GITHUB_WORKSPACE/build/*
          target: frontendDump

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_CICD_USER }}
          key: ${{ secrets.STAGING_YESK }}
          port: ${{ secrets.STAGING_PORT }}
          passphrase: ${{ secrets.STAGING_PHARSE }}
          script: |
            cp ~/frontendDump/* /var/www/specific-cif
